cmake_minimum_required(VERSION 4.3)
project(cpp_exercise)

set(CMAKE_CXX_STANDARD 20)

add_executable(cpp_exercise
        C++程序设计教程（第二版）/第一章/A1.1.cpp
        C++程序设计教程（第二版）/第一章/A1.2.cpp
        C++程序设计教程（第二版）/第一章/A1.3.cpp
        C++程序设计教程（第二版）/第一章/A1.4.cpp
        C++程序设计教程（第二版）/第一章/A1.5.cpp
        C++程序设计教程（第二版）/第一章/A1.6.cpp
        C++程序设计教程（第二版）/第一章/A1.7.cpp
        C++程序设计教程（第二版）/第三章/A3.0/A3.1.cpp
        C++程序设计教程（第二版）/第三章/A3.0/A3.2.cpp
        C++程序设计教程（第二版）/第三章/A3.0/A3.3.cpp
        C++程序设计教程（第二版）/第三章/A3.0/A3.4.cpp
        C++程序设计教程（第二版）/第三章/A3.0/A3.5.cpp
        C++程序设计教程（第二版）/第三章/A3.0/A3.6.cpp
        C++程序设计教程（第二版）/第三章/A3.0/A3.7.cpp
        C++程序设计教程（第二版）/第三章/A3.0/A3.8.cpp
        C++程序设计教程（第二版）/第三章/A3.0/A3.9.cpp
        C++程序设计教程（第二版）/第三章/A3.1/A3.10.cpp
        C++程序设计教程（第二版）/第三章/A3.1/A3.11.1.cpp
        C++程序设计教程（第二版）/第三章/A3.1/A3.11.2.cpp
        C++程序设计教程（第二版）/第三章/A3.1/A3.12.cpp
        C++程序设计教程（第二版）/第三章/A3.1/A3.13.cpp
        C++程序设计教程（第二版）/第三章/A3.1/A3.15.cpp
        C++程序设计教程（第二版）/第三章/A3.1/A3.16.cpp
        C++程序设计教程（第二版）/第三章/A3.1/A3.17.cpp
        C++程序设计教程（第二版）/第三章/A3.1/A3.18.1.cpp
        C++程序设计教程（第二版）/第三章/A3.1/A3.18.2.cpp
        C++程序设计教程（第二版）/第三章/A3.1/A3.19-2.cpp
        C++程序设计教程（第二版）/第三章/A3.1/A3.19.cpp
        C++程序设计教程（第二版）/第三章/A3.2/A3.20.cpp
        C++程序设计教程（第二版）/第三章/B/B4.1.cpp
        C++程序设计教程（第二版）/第二章/A2.2.cpp
        C++程序设计教程（第二版）/第二章/A2.3.cpp
        C++程序设计教程（第二版）/第二章/A2.4.cpp
        C++程序设计教程（第二版）/第二章/B.cpp
        C++程序设计教程（第二版）/第二章/B2.4.1.cpp
        C++程序设计教程（第二版）/第二章/B2.4.2.cpp
        C++程序设计教程（第二版）/第二章/B2.4.3.cpp
        C++程序设计教程（第二版）/第二章/B2.4.4.cpp
        "HRBUST ACM/2424/A 运费计算.cpp"
        "HRBUST ACM/2424/B 求Sn的值.cpp"
        "HRBUST ACM/2424/C 同构数.cpp"
        "HRBUST ACM/2424/D 不能被3整除的数.cpp"
        "HRBUST ACM/2424/E 打印菱形.cpp"
        "HRBUST ACM/2424/F 打印菱形2.cpp"
        "HRBUST ACM/2424/G 最强魔法师.cpp"
        "HRBUST ACM/2424/H 插入排序.cpp"
        "HRBUST ACM/2424/I 统计字符.cpp"
        "HRBUST ACM/2424/J 统计单词.cpp"
        "HRBUST ACM/2424/K 读文章.cpp"
        "HRBUST ACM/2424/L 求0的个数.cpp"
        "HRBUST ACM/2424/M 停电.cpp"
        "HRBUST ACM/2424/N RSA加密算法.cpp"
        "HRBUST ACM/2424/O Small Tiger's Love Letter.cpp"
        "HRBUST ACM/2424/P Shang Shang ans Shrimp.cpp"
        "HRBUST ACM/2424/Q Simple Math Problem.cpp"
        "HRBUST ACM/2424/R Prime Coded Lock.cpp"
        "PinTia/2021年秋季学期程序设计基础第一次考试/7.1 俊俊的大学.cpp"
        "PinTia/2021年秋季学期程序设计基础第一次考试/7.10 俊俊的船.cpp"
        "PinTia/2021年秋季学期程序设计基础第一次考试/7.11 俊俊战斗mage.cpp"
        "PinTia/2021年秋季学期程序设计基础第一次考试/7.12 宝可梦决战.cpp"
        "PinTia/2021年秋季学期程序设计基础第一次考试/7.2 Ayanoto买礼物.cpp"
        "PinTia/2021年秋季学期程序设计基础第一次考试/7.3 糖也不甜.cpp"
        "PinTia/2021年秋季学期程序设计基础第一次考试/7.4 YJJ学长的超能力.cpp"
        "PinTia/2021年秋季学期程序设计基础第一次考试/7.5 爱游泳的学长们.cpp"
        "PinTia/2021年秋季学期程序设计基础第一次考试/7.6 按开关.cpp"
        "PinTia/2021年秋季学期程序设计基础第一次考试/7.8 种田的cyh.cpp"
        "PinTia/2021年秋季学期程序设计基础第一次考试/7.9 hdh与红黑树.cpp"
        "VJudge/2026级第1-2周题单/A Hello World!.cpp"
        "VJudge/2026级第1-2周题单/B 打印字符.cpp"
        "VJudge/2026级第1-2周题单/C A+B问题.cpp"
        "VJudge/2026级第1-2周题单/D n的平方.cpp"
        "VJudge/2026级第1-2周题单/E 启蒙练习 - 函数1.cpp"
        "VJudge/2026级第1-2周题单/F 启蒙练习 - 圆的面积.cpp"
        "VJudge/2026级第1-2周题单/G 温度表达转化.cpp"
        "VJudge/2026级第1-2周题单/H 计算线段长度.cpp"
        "VJudge/2026级第1-2周题单/Hello world C.cpp"
        "VJudge/2026级第1-2周题单/I 分段函数.cpp"
        "VJudge/2026级第1-2周题单/J 西瓜.cpp"
        "VJudge/2026级第1-2周题单/K 团队.cpp"
        "VJudge/2026级第1-2周题单/L Way To Long Words.cpp"
        "VJudge/2026级第1-2周题单/M 加还是不加.cpp"
        "VJudge/2026级第1-2周题单/N 水仙花数.cpp"
        "VJudge/2026级第1-2周题单/O 蟠桃记.cpp"
        "VJudge/2026级第1-2周题单/P 多项式求和.cpp"
        "VJudge/2026级第1-2周题单/Q 素数判断.cpp"
        "VJudge/2026级第1-2周题单/R Download More RAM.cpp"
        "VJudge/2026级第1-2周题单/S 青年歌手大赛——评委会打分.cpp"
        "VJudge/2026级第三周题单/A 密码翻译.cpp"
        "VJudge/2026级第三周题单/B 首字母大写.cpp"
        "VJudge/2026级第三周题单/C 密码.cpp"
        "VJudge/2026级第三周题单/D 绝对值排序.cpp"
        "VJudge/2026级第三周题单/E 数字变位.cpp"
        "VJudge/2026级第三周题单/F 地外遗迹.cpp"
        "VJudge/2026级第三周题单/G 生日排序.cpp"
        "VJudge/2026级第三周题单/H 字符串数组排序问题.cpp"
        "VJudge/2026级第三周题单/I Palindromes_easy version.cpp"
        "VJudge/2026级第三周题单/J 进制转换.cpp"
        "VJudge/2026级第三周题单/K 人见人爱A+B.cpp"
        "VJudge/2026级第三周题单/L 人见人爱A-B.cpp"
        "VJudge/2026级第三周题单/M 人见人爱A^B.cpp"
        "VJudge/2026级第三周题单/N 亲和数.cpp"
        "VJudge/2026级第四周题单/A EZ 前缀和.cpp"
        "VJudge/2026级第四周题单/B EZ 子段求和.cpp"
        "VJudge/2026级第四周题单/C EZ 与7无关的数.cpp"
        "VJudge/2026级第四周题单/G EZ 涂气球.cpp"
        "VJudge/2026级第四周题单/L 地毯.cpp"
        "VJudge/2026级第四周题单/O 天际线.cpp"
        授课课件/test.cpp
        "洛谷/B/B20/B200/B2001 入门测试题目.cpp"
        "洛谷/B/B20/B200/B2002 Hello,World!.cpp"
        "洛谷/B/B20/B200/B2005 字符三角形.cpp"
        "洛谷/B/B20/B200/B2007 A + B 问题.cpp"
        "洛谷/B/B20/B200/B2008 计算 (a+b)×c 的值.cpp"
        洛谷/B/B20/B200/B2009.cpp
        "洛谷/B/B20/B201/B2010 带余除法.cpp"
        "洛谷/B/B20/B201/B2013 温度表达转化.cpp"
        "洛谷/B/B20/B201/B2014 与圆相关的计算.cpp"
        "洛谷/B/B20/B201/B2015 计算并联电阻的阻值.cpp"
        "洛谷/B/B20/B201/B2017 打印 ASCII 码.cpp"
        "洛谷/B/B20/B201/B2018 打印字符.cpp"
        "洛谷/B/B20/B202/B2021 输出保留 3 位小数的浮点数.cpp"
        "洛谷/B/B20/B202/B2022 输出保留 12 位小数的浮点数.cpp"
        "洛谷/B/B20/B202/B2024 输出浮点数.cpp"
        洛谷/B/B20/B202/B2025输出字符菱形.cpp
        "洛谷/B/B20/B202/B2029 大象喝水.cpp"
        "洛谷/B/B20/B203/B2034 计算 2 的幂.cpp"
        "洛谷/B/B20/B203/B2035 判断数正负.cpp"
        "洛谷/B/B20/B203/B2036 输出绝对值.cpp"
        "洛谷/B/B20/B203/B2037 奇偶数判断.cpp"
        "洛谷/B/B20/B203/B2038 奇偶 ASCII 值判断.cpp"
        "洛谷/B/B20/B203/B2039 整数大小比较.cpp"
        "洛谷/B/B20/B204/B2040 判断是否为两位数.cpp"
        "洛谷/B/B20/B204/B2041 收集瓶盖赢大奖.cpp"
        "洛谷/B/B20/B204/B2042 判断一个数能否同时被 3 和 5 整除.cpp"
        "洛谷/B/B20/B204/B2043 判断能否被 3，5，7 整除.cpp"
        "洛谷/B/B20/B204/B2044 有一门课不及格的学生.cpp"
        "洛谷/B/B20/B204/B2045 晶晶赴约会.cpp"
        "洛谷/B/B20/B204/B2046 骑车与走路.cpp"
        "洛谷/B/B20/B204/B2047 分段函数.cpp"
        "洛谷/B/B20/B204/B2048 计算邮资.cpp"
        "洛谷/B/B20/B204/B2049 最大数输出.cpp"
        "洛谷/B/B20/B205/B2050 三角形判断.cpp"
        "洛谷/B/B20/B205/B2057 最高的分数.cpp"
        "洛谷/P/P10/P100/P1000 超级玛丽游戏.cpp"
        "洛谷/P/P10/P100/P1001 A+B Problem.cpp"
        "洛谷/P/P10/P100/P1009 [NOIP 1998 普及组] 阶乘之和.cpp"
        "洛谷/P/P10/P103/P1035 [NOIP 2002 普及组] 级数求和.cpp"
        "洛谷/P/P10/P103/P1035-1 [NOIP 2002 普及组] 级数求和.cpp"
        "洛谷/P/P10/P105/P1055 [NOIP 2008 普及组] ISBN 号码.cpp"
        "洛谷/P/P11/P115/P1150 Peter 的烟.cpp"
        "洛谷/P/P13/P130/P1307 [NOIP 2011 普及组] 数字反转.cpp"
        "洛谷/P/P14/P142/P1421 小玉买文具.cpp"
        "洛谷/P/P14/P142/P1422 小玉家的电费.cpp"
        "洛谷/P/P14/P142/P1423 小玉在游泳.cpp"
        "洛谷/P/P14/P142/P1425 小鱼的游泳时间.cpp"
        "洛谷/P/P14/P146/P1469 找筷子.cpp"
        "洛谷/P/P18/P188/P1888 三角函数.cpp"
        "洛谷/P/P24/P243/P2433 【深基1-2】小学数学 N 合一.cpp"
        "洛谷/P/P39/P395/P3954 [NOIP 2017 普及组] 成绩.cpp"
        "洛谷/P/P44/P441/P4414 [COCI 2006-2007 #2] ABC.cpp"
        "洛谷/P/P57/P570/P5703 【深基2.例5】苹果采购.cpp"
        "洛谷/P/P57/P570/P5704 【深基2.例6】字母转换.cpp"
        "洛谷/P/P57/P570/P5705 【深基2.例7】数字反转.cpp"
        "洛谷/P/P57/P570/P5706 【深基2.例8】再分肥宅水.cpp"
        "洛谷/P/P57/P570/P5707 【深基2.例12】上学迟到.cpp"
        "洛谷/P/P57/P570/P5708 【深基2.习2】三角形面积.cpp"
        "洛谷/P/P57/P570/P5709 【深基2.习6】苹果和虫子.cpp"
        "洛谷/P/P57/P571/P5710 【深基3.例2】数的性质.cpp"
        "洛谷/P/P57/P571/P5711 【深基3.例3】闰年判断.cpp"
        "洛谷/P/P57/P571/P5712 【深基3.例4】Apples.cpp"
        "洛谷/P/P57/P571/P5714 【深基3.例7】肥胖问题.cpp"
        "洛谷/P/P57/P571/P5716 【深基3.例9】月份天数.cpp"
        "洛谷/P/P57/P571/P5717 三角形分类.cpp"
        "洛谷/P/P57/P571/P5718 【深基4.例2】找最小值.cpp"
        "洛谷/P/P57/P571/P5719 【深基4.例3】分类平均.cpp"
        "洛谷/P/P57/P572/P5722 【深基4.例11】数列求和.cpp"
        "洛谷/P/P57/P573/P5733 【深基6.例1】自动修正.cpp"
        "洛谷/P/P57/P573/P5735 【深基7.例1】距离函数.cpp"
        "牛客/noob/00/000/1 Hello Nowcoder.cpp"
        "牛客/noob/00/000/2 牛牛学说话之 - 整数.cpp"
        "牛客/noob/00/000/3 牛牛学说话之 - 浮点数.cpp"
        "牛客/noob/00/000/4 牛牛学说话之 - 字符串.cpp"
        "牛客/noob/00/000/5 复读机.cpp"
        "牛客/noob/00/000/6 牛牛学加法.cpp"
        "牛客/noob/00/000/7 疫情死亡率.cpp"
        "牛客/noob/00/000/8 计算带余除法.cpp"
        "牛客/noob/00/000/9 整数的个位.cpp"
        "牛客/noob/00/001/10 整数的十位.cpp"
        "牛客/noob/00/001/11 平方根.cpp"
        "牛客/noob/00/001/12 反向输出一个四位数.cpp"
        "牛客/noob/00/001/13 温标转换.cpp"
        "牛客/noob/00/001/14 绕距.cpp"
        "牛客/noob/00/001/15 求四位数各个数位之和.cpp"
        "牛客/noob/00/001/16 时间转换.cpp"
        "牛客/noob/00/001/17 计算机内存.cpp"
        "牛客/noob/00/001/18 牛牛学立体.cpp"
        "牛客/noob/00/001/19 成绩.cpp"
        "牛客/noob/00/002/20 小乐乐求和.cpp"
        "牛客/noob/00/002/21 明天星期几.cpp"
        "牛客/noob/00/002/22 判断闰年.cpp"
        "牛客/noob/00/002/23 比大小.cpp"
        "牛客/noob/00/002/24 卡拉兹函数.cpp"
        "牛客/noob/00/002/25 牛妹数.cpp"
        "牛客/noob/00/002/26 牛牛是否被叫家长.cpp"
        "牛客/noob/00/002/27 最大最小值.cpp"
        "牛客/noob/00/002/28 四季.cpp"
        "牛客/noob/00/002/29 多组输入 a+b II.cpp"
        "牛客/noob/00/003/30 多组数据 a+b III.cpp"
        "牛客/noob/00/003/31 素数判断.cpp"
        "牛客/noob/00/003/32 牛牛学数列.cpp"
        "牛客/noob/00/003/33 牛牛学数列2.cpp"
        "牛客/noob/00/003/34 最大的差.cpp"
        "牛客/noob/00/003/35 牛牛学数列4.cpp"
        "牛客/noob/00/003/36 牛牛学数列5.cpp"
        "牛客/noob/00/003/37 数列之和.cpp"
        "牛客/noob/00/003/38 牛牛数数.cpp"
        "牛客/noob/00/003/39 牛牛学数列6.cpp"
        "牛客/noob/00/004/40 二维斐波那契数列.cpp"
        "牛客/noob/00/004/41 神秘石像的镜像序列.cpp"
        "牛客/noob/00/004/42 左侧严格小于计数.cpp"
        "牛客/noob/00/004/43 牛牛的数学作业.cpp"
        牛客/哈理工ACM协会训练题单/A.cpp
        牛客/哈理工ACM协会训练题单/B.cpp
        牛客/哈理工ACM协会训练题单/C.cpp
        牛客/哈理工ACM协会训练题单/D.cpp
        牛客/哈理工ACM协会训练题单/E.cpp
        牛客/哈理工ACM协会训练题单/F.cpp
        牛客/哈理工ACM协会训练题单/G.cpp
        "牛客/第一次培训题单/A 前缀和.cpp"
        "牛客/第一次培训题单/B 二维前缀和.cpp"
        "牛客/第一次培训题单/C 差分.cpp"
        "牛客/第二次培训 简单版/A 走出迷宫.cpp"
        蓝桥杯/“萌新首秀”千校新生编程排位赛/第一场/2.新生保护计划.cpp
        "计蒜客/T/T10/T100/T1001 计算A+B.cpp"
        "计蒜客/T/T10/T100/T1003 输出字符菱形.cpp"
        "计蒜客/T/T10/T100/T1004 输出Hello,World!.cpp"
        "计蒜客/T/T10/T100/T1005 输出字符三角形.cpp"
        "VJudge/2026级第5周题单/A 斐波那契数列.cpp"
        "VJudge/2026级第5周题单/B 数楼梯.cpp"
        "VJudge/2026级第5周题单/C 数字三角形.cpp"
        "VJudge/2026级第5周题单/D 快速幂.cpp"
        "VJudge/2026级第5周题单/E 数的计算.cpp"
        "VJudge/2026级第5周题单/F 选数.cpp"
        "VJudge/2026级第5周题单/G Function.cpp"
        "VJudge/2026级第5周题单/H 数的划分.cpp"
        "VJudge/2026级第5周题单/I 全排列问题.cpp"
        "VJudge/2026级第5周题单/J 逆序对.cpp"
        "VJudge/2026级第5周题单/K 求第k小的数.cpp"
        "VJudge/2026级第5周题单/L 外星密码.cpp"
        "VJudge/2026级第5周题单/M Can you answer these queries I.cpp"
        "VJudge/2026级第5周题单/N 平面上的最接近点对.cpp"
        "VJudge/2026级第5周题单/O 平面最近点对（Pro）.cpp"
        "VJudge/2026级第5周题单/P 平面最近点对（Max）.cpp")
